# Generated by Django 3.0 on 2019-12-23 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('locationID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('locationName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amendedPN', models.CharField(blank=True, max_length=10)),
                ('gaiaPN', models.CharField(blank=True, max_length=10)),
                ('SgPN', models.CharField(blank=True, max_length=40)),
                ('supplementaryPN', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('productCategory', models.CharField(choices=[('aaa', 'null'), ('ASH', 'AIR|SHIELD™'), ('AMA', 'AIR|MAT™'), ('APA', 'AIR|PAKK™'), ('CCA', 'Corr Case '), ('TCO', 'TRANS|COVER'), ('TCA', 'TRANS|CASE ')], default='aaa', max_length=3)),
                ('isManual', models.BooleanField()),
                ('filmThickness', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('A', 'Active')], default='A', max_length=1)),
                ('cylinderSequence', models.CharField(blank=True, max_length=30)),
                ('sealingSequence', models.CharField(blank=True, max_length=30)),
                ('USDCostPrice', models.FloatField(blank=True, max_length=8)),
                ('deliveredDutyGBP', models.FloatField(blank=True, max_length=8)),
                ('gaiaSellPrice', models.FloatField(blank=True, max_length=8)),
                ('samuelGrantPurchasePrice', models.FloatField(blank=True, max_length=8)),
                ('samuelGrantBuyback', models.IntegerField(blank=True)),
                ('PCSPerObject', models.IntegerField(blank=True)),
                ('amountPerPallet', models.IntegerField(blank=True)),
                ('minimumOrderQuantity', models.IntegerField(blank=True)),
                ('deflatedWidth', models.IntegerField(blank=True)),
                ('deflatedLength', models.IntegerField(blank=True)),
                ('deflatedHeight', models.IntegerField(blank=True)),
                ('inflatedWidth', models.IntegerField(blank=True)),
                ('inflatedLength', models.IntegerField(blank=True)),
                ('inflatedHeight', models.IntegerField(blank=True)),
                ('CTNAmountPerPallet', models.IntegerField(blank=True)),
                ('CTNWidth', models.IntegerField(blank=True)),
                ('CTNLength', models.IntegerField(blank=True)),
                ('CTNHeight', models.IntegerField(blank=True)),
                ('netWeight', models.FloatField(blank=True, max_length=5)),
                ('grossWeight', models.FloatField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('supplierID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('supplierName', models.CharField(max_length=100)),
                ('supplierNumber', models.IntegerField()),
                ('supplierEmail', models.CharField(max_length=254)),
                ('companyNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='productStockStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('MasterPN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseFunctions.product')),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseFunctions.locations')),
                ('supplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseFunctions.suppliers')),
            ],
        ),
    ]
