# Generated by Django 3.0 on 2019-12-05 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('productCategoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('productCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('locationID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('locationName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('masterPN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('amendedPN', models.CharField(max_length=10)),
                ('gaiaPN', models.CharField(max_length=10)),
                ('SgPN', models.CharField(max_length=40)),
                ('supplementaryPN', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('isManual', models.BooleanField()),
                ('filmThickness', models.IntegerField()),
                ('cylinderSequence', models.CharField(max_length=30)),
                ('sealingSequence', models.CharField(max_length=30)),
                ('USDCostPrice', models.FloatField(max_length=8)),
                ('deliveredDutyGBP', models.FloatField(max_length=8)),
                ('gaiaSellPrice', models.FloatField(max_length=8)),
                ('samuelGrantPurchasePrice', models.FloatField(max_length=8)),
                ('samuelGrantBuyback', models.IntegerField()),
                ('PCSPerObject', models.IntegerField()),
                ('amountPerPallet', models.IntegerField()),
                ('minimumOrderQuantity', models.IntegerField()),
                ('deflatedWidth', models.IntegerField()),
                ('deflatedLength', models.IntegerField()),
                ('deflatedHeight', models.IntegerField()),
                ('inflatedWidth', models.IntegerField()),
                ('inflatedLength', models.IntegerField()),
                ('inflatedHeight', models.IntegerField()),
                ('CTNAmountPerPallet', models.IntegerField()),
                ('CTNWidth', models.IntegerField()),
                ('CTNLength', models.IntegerField()),
                ('CTNHeight', models.IntegerField()),
                ('netWeight', models.FloatField(max_length=5)),
                ('grossWeight', models.FloatField(max_length=5)),
                ('productCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseFunctions.categories')),
            ],
        ),
        migrations.CreateModel(
            name='spreadsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('spreadsheet', models.FileField(upload_to='static/documents')),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='statuses',
            fields=[
                ('statusID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('supplierID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('supplierName', models.CharField(max_length=100)),
                ('supplierNumber', models.IntegerField()),
                ('supplierEmail', models.CharField(max_length=254)),
                ('companyNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='productStockStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('MasterPN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseFunctions.product')),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseFunctions.locations')),
                ('supplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseFunctions.suppliers')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='statusID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseFunctions.statuses'),
        ),
    ]
