# Generated by Django 3.0.1 on 2019-12-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseFunctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='netWeight',
            new_name='nettWeight',
        ),
    ]
