# Generated by Django 3.0.1 on 2020-01-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseFunctions', '0002_auto_20200103_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
