# Generated by Django 3.0.1 on 2019-12-27 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseFunctions', '0002_auto_20191227_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='STATUS',
        ),
    ]
