# Generated by Django 3.0 on 2019-12-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseFunctions', '0002_auto_20191207_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
    ]
