# Generated by Django 3.0.1 on 2020-01-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseFunctions', '0003_remove_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CP',
            field=models.FloatField(blank=True, default=-1, max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='CTNAmountPerPallet',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='CTNHeight',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='CTNLength',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='CTNWidth',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='DDP',
            field=models.FloatField(blank=True, default=-1, max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='GAIAPN',
            field=models.CharField(blank=True, default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='GAIASP',
            field=models.FloatField(blank=True, default=-1, max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='MOQ',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='PCSPerPallet',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='PCSPerRoll',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='SGBB',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='SGPP',
            field=models.FloatField(blank=True, default=-1, max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='SgPN',
            field=models.CharField(blank=True, default='null', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='amendedPN',
            field=models.CharField(blank=True, default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='cylinderSequence',
            field=models.CharField(blank=True, default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='deflatedHeight',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='deflatedLength',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='deflatedWidth',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='null'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filmThickness',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='grossWeight',
            field=models.FloatField(blank=True, default=-1, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='inflatedHeight',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='inflatedLength',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='inflatedWidth',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='isManual',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nettWeight',
            field=models.FloatField(blank=True, default=-1, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sealingSequence',
            field=models.CharField(blank=True, default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplementaryPN',
            field=models.CharField(blank=True, default='null', max_length=40),
        ),
    ]
