# Generated by Django 3.0 on 2019-12-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseFunctions', '0004_document_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productCategoryID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='statusID',
        ),
        migrations.AddField(
            model_name='product',
            name='productCategory',
            field=models.CharField(choices=[('aaa', 'null'), ('ASH', 'AIR|SHIELD™'), ('AMA', 'AIR|MAT™'), ('APA', 'AIR|PAKK™'), ('CCA', 'Corr Case '), ('TCO', 'TRANS|COVER'), ('TCA', 'TRANS|CASE ')], default='aaa', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('A', 'Active')], default='A', max_length=1),
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='statuses',
        ),
    ]
