# Generated by Django 3.0 on 2019-12-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseFunctions', '0005_auto_20191211_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CTNAmountPerPallet',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='CTNHeight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='CTNLength',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='CTNWidth',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='PCSPerObject',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SgPN',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='USDCostPrice',
            field=models.FloatField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='amendedPN',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='amountPerPallet',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cylinderSequence',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='deflatedHeight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deflatedLength',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deflatedWidth',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deliveredDutyGBP',
            field=models.FloatField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filmThickness',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gaiaPN',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='gaiaSellPrice',
            field=models.FloatField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='grossWeight',
            field=models.FloatField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='inflatedHeight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='inflatedLength',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='inflatedWidth',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimumOrderQuantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='netWeight',
            field=models.FloatField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='samuelGrantBuyback',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='samuelGrantPurchasePrice',
            field=models.FloatField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='sealingSequence',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplementaryPN',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
