# Generated by Django 3.0.3 on 2020-02-08 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databaseFunctions', '0005_auto_20200112_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityLocation', models.CharField(choices=[('aaa', 'null')], default='aaa', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='productHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productDate', models.DateField(auto_now_add=True)),
                ('openingBalance', models.IntegerField()),
                ('forecastedUsage', models.IntegerField(null=True)),
                ('facilityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphingModule.facilities')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseFunctions.product')),
            ],
            options={
                'unique_together': {('productDate', 'productID')},
            },
        ),
    ]
