# Generated by Django 3.0.1 on 2020-01-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databaseFunctions', '0005_auto_20200112_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacilityLocation', models.CharField(choices=[('aaa', 'null')], default='aaa', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='productHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productDate', models.DateField(auto_now_add=True)),
                ('OpeningBalance', models.IntegerField()),
                ('ForecastedUsage', models.IntegerField(null=True)),
                ('FacilityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphingModule.Facilities')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseFunctions.product')),
            ],
            options={
                'unique_together': {('productDate', 'productID')},
            },
        ),
    ]
